environment:

  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

platform:
    - x64

install:
    - sh: cd src/
    - sh: mkdir nr
    - sh: cd nr/
    - sh: wget -O nr.tar.gz https://zhanglab.ccmb.med.umich.edu/cgi-bin/download_ftp.cgi?ID=nr.tar.gz
    - sh: tar -zxvf nr.tar.gz
    - sh: cd ../PSSpred_v4/
    - sh: perl PSSpred.pl seq.fasta
    - sh: perl -MDevel::Cover=-db,/home/travis/build/nickcafferry/PSSpred/src/PSSpred_v4/cover_db PSSpred.pl   
    - sh: pwd

# Skip .NET project specific build phase.
build: off

test_script:
    - "pwd"


#artifacts:
#  - path: test.zip
#    name: MyApp
