image: Ubuntu

install:
    - sh: cd src/
    - sh: mkdir nr
    - sh: cd nr/
    - sh: wget -O nr.tar.gz https://zhanglab.ccmb.med.umich.edu/cgi-bin/download_ftp.cgi?ID=nr.tar.gz
    - sh: tar -zxvf nr.tar.gz
    - sh: cd ../PSSpred_v4/
    - sh: ./PSSpred.pl seq.fasta
    - sh: pwd

# Skip .NET project specific build phase.
build: off

test_script:
    - "ls"
    - "pwd"

artifacts:
  - path: src\PSSpred_v4\seq.dat
    name: seq.dat
  
  - path: src\PSSpred_v4\seq.dat.ss
    name: seq.dat.ss
  
  - path: src\PSSpred_v4\blast.out
    name: blast.out
