environment:

  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64

platform:
    - x64

install:
    - sh: cd src/
    - sh: mkdir nr
    - sh: cd nr/
    - sh: wget -O nr.tar.gz https://zhanglab.ccmb.med.umich.edu/cgi-bin/download_ftp.cgi?ID=nr.tar.gz
    - sh: tar -zxvf nr.tar.gz
    - sh: cd ../PSSpred_v4/
    - sh: perl PSSpred.pl seq.fasta
    - sh: pwd

# Skip .NET project specific build phase.
build: off

test_script:
    - "ls"
    - "cd src/PSSpred_v4/"
    - "ls"
    - "pwd"

artifacts:
  - path: /c/projects/psspred/src/PSSpred_v4/seq.dat
    name: seq.dat
  
  - path: /c/projects/psspred/src/PSSpred_v4/seq.dat.ss
    name: seq.dat.ss
  
  - path: /c/projects/psspred/src/PSSpred_v4/blast.out
    name: blast.out
