name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls
        echo '======================='
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"

        you-get -o ./you_get/ --debug 'http://open.163.com/newview/movie/free?pid=M6TUCF6FT&mid=M6TUCLS2K'
        you-get -o ./you_get/ --debug 'http://open.163.com/newview/movie/free?pid=M6TUCF6FT&mid=M6TUCR7GA' 
        you-get -o ./you_get/ --debug 'http://open.163.com/newview/movie/free?pid=M6TUCF6FT&mid=M6TUCS2CU'
        you-get -o ./you_get/ --debug 'http://open.163.com/newview/movie/free?pid=M6TUCF6FT&mid=M6TUCSC7V'         

  
        ls
        echo '------------------------------'
        cd you_get
        ls 
        echo '~~~~~~~~~~~~~~~~~~~~~~'
        cd ../

        cp -r you_get/. Working-of-an-acid-buffer/videos/Principal_of_Chemical_Science/
        cd Working-of-an-acid-buffer/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd videos/Principal_of_Chemical_Science/
        git add -A
        git status 
        git commit -m "Add some videos"
        ls
        git push origin master

