name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls
        echo '======================='
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"

        you-get -o ./you_get/ --debug 'http://mov.bn.netease.com/open-movie/nos/mp4/2015/04/08/SALO80IJ2_sd.mp4'
        you-get -o ./you_get/ --debug 'http://mov.bn.netease.com/open-movie/nos/mp4/2015/04/08/SALO80VNS_sd.mp4'
        
        ls
        echo '------------------------------'
        cd you_get
        ls 
        echo '~~~~~~~~~~~~~~~~~~~~~~'
        cd ../

        cd you_get/
        ls
        pwd
        
    - uses: actions/upload-artifact@v2
      with:
        name: quantum videos
        path: /home/runner/work/Working-of-an-acid-buffer/you_get/

