name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls
        echo '======================='
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=1' 
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=2'
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=3'
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=4'
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=5'
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=6'
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=7'
        you-get -o ./you_get/ --debug 'https://www.bilibili.com/video/BV1vJ411X72C?p=8'

        ls
        echo '------------------------------'
        cd you_get
        ls 
        echo '~~~~~~~~~~~~~~~~~~~~~~'
        cd ../
        mkdir Working-of-an-acid-buffer/videos
        cp -r you_get/. Working-of-an-acid-buffer/videos
        cd Working-of-an-acid-buffer/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd videos/
        git add -A
        git status 
        git commit -m "Add some videos"
        ls
        git push origin master

