name: PSSpred

on:
  push:
    branches:
      - master

#jobs:
#  build_docs_and_deploy:
#    runs-on: ubuntu-latest
#    name: Protein Secondary Structure prediction
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@master
#
#    - name: Clone pre repositories
#      run: |
#         git config --global user.email "ucecwme@ucl.ac.uk"
#         git config --global user.name "nickcafferry"
#         git init
#         git lfs install
#         echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
#         git lfs pull
#         ls
#         mkdir src
#         cd src/
#         wget https://zhanglab.ccmb.med.umich.edu/PSSpred/PSSpred_v4.tar.bz2
#         tar -jxvf PSSpred_v4.tar.bz2
#         ls
#         git add -A
#         git commit -m "add PSSred"
#         pwd
#         cd ../
#         git push origin master
